modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="randomflower"
version="20.1.0.13"
displayName="Random Flower"
authors="mcjinmouren, zhirumo"
description='''It ports some flowers from ExtraBotany'''
[[dependencies.randomflower]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.randomflower]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.randomflower]]
modId="botania"
mandatory=true
versionRange="(1.20.1-446,]"
ordering="NONE"
side="BOTH"
[[dependencies.randomflower]]
modId="curios"
mandatory=true
versionRange="(5.9,]"
ordering="NONE"
side="BOTH"
[[dependencies.randomflower]]
modId="patchouli"
mandatory=true
versionRange="(1.20.1-80,]"
ordering="NONE"
side="BOTH"
